# Generated by Django 3.0.8 on 2022-05-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_change_UserModel'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='team',
            field=models.CharField(default='', max_length=14),
        ),
    ]
