# Generated by Django 3.0.8 on 2022-05-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
