# Generated by Django 4.0.5 on 2022-06-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_team_column_to_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='refresh_token',
            field=models.TextField(blank=True),
        ),
    ]
