# Generated by Django 4.0.5 on 2022-06-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_myuser_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='denied_access_token',
            field=models.TextField(blank=True),
        ),
    ]
